platform_testing:
  s3_tfstate_backend: false
  vpc: false
  kms: false
  ssh_key_pair: false
  bastion: false
  iam_role_codebuild: false
  iam_role_codepipeline: false
  iam_role_eks_worker: false
  iam_role_efs_provisioner: false
  iam_role_eks_cluster: false
  iam_role_lambda_common: false
  iam_role_rds_monitoring: false
  route53_cluster_zone: false
  route53_zone_and_records: false
  core_security_group: false
  ecr: false
  efs: false
  rds_cluster_aurora: false
  eks: true
  codepipeline_s3_bucket: false
  codepipeline_umsl: false
dataops_dev:
  s3_tfstate_backend: false
  codepipeline_s3_bucket: false
  s3_bucket: false
  s3_iam_user: false
  s3_load_balance_log: false
  s3_log_storage: false
  vpc: false
  kms: false
  ssh_key_pair: false
  tls_key_pair: false
  ssm_key_pair: false
  iam_role_codebuild: false
  iam_role_codepipeline: false
  iam_role_eks_worker: false
  iam_role_efs_provisioner: false
  iam_role_eks_cluster: false
  iam_role_lambda_common: false
  iam_role_rds_monitoring: false
  iam_system_user: false
  iam_role_vpc_peering_cross_account: false
  lambda_product_image_copy: false
  lambda_nextail_transfer: false
  lambda_nextail_transfer_s3_ownership: false
  lambda_storemaster_datalake: false
  lambda_storemaster: false
  lambda_sns_to_slack_alerts: false
  lambda_price_product_backbone: false
  lambda_price_monitor_nextail: false
  route53_zone_and_records: false
  vpc_peering_to_transit: false
  vpc_peering_cross_account: false
  vpc_same_account_peering: false
  route53_cluster_zone: false
  core_security_group: false
  ecr: false
  bastion: false
  jenkins_master: false
  rds_cluster_aurora: false
  efs: false
  eks: false
  codepipeline: false
dataops_staging:
  s3_tfstate_backend: false
  codepipeline_s3_bucket: false
  s3_bucket: false
  s3_iam_user: false
  s3_load_balance_log: false
  s3_log_storage: false
  vpc: false
  kms: false
  ssh_key_pair: false
  tls_key_pair: false
  ssm_key_pair: false
  iam_role_codebuild: false
  iam_role_codepipeline: false
  iam_role_eks_worker: false
  iam_role_efs_provisioner: false
  iam_role_eks_cluster: false
  iam_role_lambda_common: false
  iam_role_rds_monitoring: false
  iam_system_user: false
  iam_role_vpc_peering_cross_account: false
  lambda_product_image_copy: false
  lambda_nextail_transfer: false
  lambda_nextail_transfer_s3_ownership: false
  lambda_storemaster_datalake: false
  lambda_storemaster: false
  lambda_sns_to_slack_alerts: false
  lambda_price_product_backbone: false
  lambda_price_monitor_nextail: false
  route53_zone_and_records: false
  vpc_peering_to_transit: false
  vpc_peering_cross_account: false
  vpc_same_account_peering: false
  route53_cluster_zone: false
  core_security_group: false
  ecr: false
  bastion: false
  jenkins_master: false
  rds_cluster_aurora: false
  efs: false
  eks: false
  codepipeline: true
dataops_prod:
  s3_tfstate_backend: false
  codepipeline_s3_bucket: false
  s3_bucket: false
  s3_iam_user: false
  s3_load_balance_log: false
  s3_log_storage: false
  vpc: false
  kms: false
  ssh_key_pair: false
  tls_key_pair: false
  ssm_key_pair: false
  iam_role_codebuild: false
  iam_role_codepipeline: false
  iam_role_eks_worker: false
  iam_role_efs_provisioner: false
  iam_role_eks_cluster: false
  iam_role_lambda_common: false
  iam_role_rds_monitoring: false
  iam_system_user: false
  iam_role_vpc_peering_cross_account: false
  lambda_product_image_copy: false
  lambda_nextail_transfer: false
  lambda_nextail_transfer_s3_ownership: false
  lambda_storemaster_datalake: false
  lambda_storemaster: false
  lambda_sns_to_slack_alerts: false
  lambda_price_product_backbone: false
  lambda_price_monitor_nextail: false
  route53_zone_and_records: false
  vpc_peering_to_transit: false
  vpc_peering_cross_account: false
  vpc_same_account_peering: false
  route53_cluster_zone: false
  core_security_group: false
  ecr: false
  bastion: false
  jenkins_master: false
  rds_cluster_aurora: false
  efs: false
  eks: false
  codepipeline: false

